In [45]:
import pandas as pd
import numpy as np

In [142]:
Customers = pd.read_csv("Customers.csv")
Orders = pd.read_csv("Orders.csv")
Order_Items = pd.read_csv("Order_Items.csv")
Products = pd.read_csv("Products.csv")
Payments = pd.read_csv("Payments.csv")

In [7]:
print(Customers.shape)
print(Orders.shape)
print(Order_Items.shape)
print(Products.shape)
print(Payments.shape)

(25500, 4)
(101000, 3)
(180000, 5)
(8000, 5)
(100000, 4)

In [13]:
Customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25500 entries, 0 to 25499
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    25500 non-null  object
 1   customer_name  25500 non-null  object
 2   city           22257 non-null  object
 3   email          23957 non-null  object
dtypes: object(4)
memory usage: 797.0+ KB

In [14]:
Orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   order_id     101000 non-null  object
 1   customer_id  101000 non-null  object
 2   status       84344 non-null   object
dtypes: object(3)
memory usage: 2.3+ MB

In [15]:
Order_Items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180000 entries, 0 to 179999
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_item_id  180000 non-null  object
 1   order_id       180000 non-null  object
 2   product_id     180000 non-null  object
 3   quantity       180000 non-null  int64
 4   unit_price     179000 non-null  float64
dtypes: float64(1), int64(1), object(3)
memory usage: 6.9+ MB

In [16]:
Products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product_id  8000 non-null   object
 1   category    6879 non-null   object
 2   price       8000 non-null   float64
 3   brand       6635 non-null   object
 4   stock       8000 non-null   int64
dtypes: float64(1), int64(1), object(3)
memory usage: 312.6+ KB

In [17]:
Payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   payment_id      100000 non-null  object
 1   order_id        100000 non-null  object
 2   payment_method  83450 non-null   object
 3   amount          98800 non-null   float64
dtypes: float64(1), object(3)
memory usage: 3.1+ MB

In [88]:
Customers.isnull().sum()

customer_id         0
customer_name       0
city                0
email            1500
dtype: int64

In [19]:
Orders.isnull().sum()

order_id           0
customer_id        0
status         16656
dtype: int64

In [21]:
Order_Items.isnull().sum()

order_item_id       0
order_id            0
product_id          0
quantity            0
unit_price       1000
dtype: int64

In [22]:
Payments.isnull().sum()

payment_id            0
order_id              0
payment_method    16550
amount             1200
dtype: int64

In [23]:
Products.isnull().sum()

product_id       0
category      1121
price            0
brand         1365
stock            0
dtype: int64

In [24]:
Customers.duplicated().sum()

np.int64(500)

In [25]:
Orders.duplicated().sum()

np.int64(1000)

In [26]:
Order_Items.duplicated().sum()

np.int64(0)

In [27]:
Products.duplicated().sum()

np.int64(0)

In [94]:
Payments.duplicated().sum()

np.int64(0)

In [ ]:
# Cleaning Customers Table

In [63]:
Customers.head(10)

  customer_id customer_name       city           email
0     C000000    Customer 0             user0@mail.com
1     C000001    Customer 1       Pune  user1@mail.com
2     C000002    Customer 2     mumbai  user2@mail.com
3     C000003    Customer 3        NaN  user3@mail.com
4     C000004    Customer 4  Bengaluru  user4@mail.com
5     C000005    Customer 5  Bengaluru  user5@mail.com
6     C000006    Customer 6             user6@mail.com
7     C000007    Customer 7             user7@mail.com
8     C000008    Customer 8       Pune  user8@mail.com
9     C000009    Customer 9     mumbai  user9@mail.com

In [30]:
Orders.head(10)

   order_id customer_id     status
0  O0000000     C024504   Returned
1  O0000001     C018974  Delivered
2  O0000002     C001586  delivered
3  O0000003     C003069   Returned
4  O0000004     C011950    Shipped
5  O0000005     C024666        NaN
6  O0000006     C009706  Delivered
7  O0000007     C009825  delivered
8  O0000008     C019388  Cancelled
9  O0000009     C003425        NaN

In [32]:
Order_Items.head(10)

  order_item_id  order_id product_id  quantity  unit_price
0     OI0000000  O0032043    P003863        -2      780.23
1     OI0000001  O0074941    P006941         4     4621.80
2     OI0000002  O0001286    P002596         4     4355.11
3     OI0000003  O0077083    P001424         6     2432.98
4     OI0000004  O0027593    P000030         5      404.45
5     OI0000005  O0056430    P000933         4     4743.18
6     OI0000006  O0028969    P004070         3     2344.67
7     OI0000007  O0079938    P004192        -1     3469.39
8     OI0000008  O0010967    P007213        -2     1251.53
9     OI0000009  O0043330    P006526         2     3397.56

In [33]:
Products.head(10)

  product_id     category    price    brand  stock
0    P000000      Fashion   889.61     Sony    621
1    P000001  Electronics   313.84     Boat    465
2    P000002      Fashion   607.57     Boat    153
3    P000003       Beauty   168.39     Boat    956
4    P000004  electronics   900.85  Samsung    913
5    P000005         Home   136.93     Sony     85
6    P000006      Fashion  2036.65      NaN    520
7    P000007          NaN   349.10  Samsung    820
8    P000008  Electronics   576.32     Nike    639
9    P000009      Fashion   429.67  Samsung    292

In [35]:
Payments.head(10)

   payment_id  order_id payment_method    amount
0  PAY0000000  O0070490            COD   4096.82
1  PAY0000001  O0034779            COD   5799.97
2  PAY0000002  O0028911     NetBanking   5015.29
3  PAY0000003  O0022101           Card  11844.77
4  PAY0000004  O0054735            COD   9103.55
5  PAY0000005  O0037884            COD  14291.15
6  PAY0000006  O0085088            UPI   5127.50
7  PAY0000007  O0079483            UPI  19996.87
8  PAY0000008  O0091966            upi    561.58
9  PAY0000009  O0018570            upi   5448.48

In [69]:
Customers = Customers.drop_duplicates()

In [70]:
Customers.duplicated().sum()

np.int64(0)

In [83]:
Customers["city"] = Customers["city"].str.strip()
Customers["city"] = Customers["city"].str.title()

In [72]:
Customers["city"] = Customers["city"].replace("", np.nan)

In [73]:
Customers["city"].value_counts(dropna=False)

city
Mumbai       6334
NaN          6259
Bengaluru    3176
Chennai      3134
Delhi        3108
Pune         2989
Name: count, dtype: int64

In [80]:
Customers["city"] = Customers["city"].fillna("Unknown")

In [75]:
Customers["email"].isnull().sum()

np.int64(1500)

In [60]:
# Backup/ Recovery File
# Customers_original = pd.read_csv("Customers.csv")
# Customers["email"] = Customers_original["email"]
# Customers["email"].isnull().sum()

In [89]:
Customers.isnull().sum()

customer_id         0
customer_name       0
city                0
email            1500
dtype: int64

In [86]:
Customers.head(10)

  customer_id customer_name       city           email
0     C000000    Customer 0    Unknown  user0@mail.com
1     C000001    Customer 1       Pune  user1@mail.com
2     C000002    Customer 2     Mumbai  user2@mail.com
3     C000003    Customer 3    Unknown  user3@mail.com
4     C000004    Customer 4  Bengaluru  user4@mail.com
5     C000005    Customer 5  Bengaluru  user5@mail.com
6     C000006    Customer 6    Unknown  user6@mail.com
7     C000007    Customer 7    Unknown  user7@mail.com
8     C000008    Customer 8       Pune  user8@mail.com
9     C000009    Customer 9     Mumbai  user9@mail.com

In [91]:
Customers.to_csv("Customers_Clean.csv", index=False)

In [ ]:
# Cleaning Orders Table

In [96]:
Orders.head(10)

   order_id customer_id     status
0  O0000000     C024504   Returned
1  O0000001     C018974  Delivered
2  O0000002     C001586  delivered
3  O0000003     C003069   Returned
4  O0000004     C011950    Shipped
5  O0000005     C024666        NaN
6  O0000006     C009706  Delivered
7  O0000007     C009825  delivered
8  O0000008     C019388  Cancelled
9  O0000009     C003425        NaN

In [97]:
Orders.isnull().sum()

order_id           0
customer_id        0
status         16481
dtype: int64

In [108]:
Orders = Orders.drop_duplicates()
Orders.duplicated().sum()

np.int64(0)

In [101]:
Orders["status"].value_counts(dropna=False)

status
Shipped      16860
delivered    16706
Returned     16687
Delivered    16684
Cancelled    16582
NaN          16481
Name: count, dtype: int64

In [104]:
Orders["status"] = Orders["status"].str.title()

In [107]:
Orders["status"].value_counts(dropna=False) 
# false mtlb nan bhi dikhao

status
Delivered    33390
Shipped      16860
Returned     16687
Cancelled    16582
Unknown      16481
Name: count, dtype: int64

In [106]:
Orders["status"] = Orders["status"].fillna("Unknown")

In [109]:
Orders.to_csv("Orders_Clean.csv", index=False)

In [110]:
# Cleaning Order_Items Table

In [119]:
Order_Items.head(10)

   order_item_id  order_id product_id  quantity  unit_price
1      OI0000001  O0074941    P006941         4     4621.80
2      OI0000002  O0001286    P002596         4     4355.11
3      OI0000003  O0077083    P001424         6     2432.98
4      OI0000004  O0027593    P000030         5      404.45
5      OI0000005  O0056430    P000933         4     4743.18
6      OI0000006  O0028969    P004070         3     2344.67
9      OI0000009  O0043330    P006526         2     3397.56
10     OI0000010  O0074646    P000806         2     3570.48
11     OI0000011  O0064241    P007978         7     2457.48
12     OI0000012  O0056835    P000356         6       85.63

In [114]:
(Order_Items["quantity"] < 0).sum()

np.int64(36137)

In [120]:
Order_Items ["quantity"].value_counts().sort_index()

quantity
1    17984
2    18011
3    17965
4    17914
5    17972
6    18030
7    17936
Name: count, dtype: int64

In [121]:
Order_Items[Order_Items["quantity"] <= 0].shape

(0, 5)

In [122]:
Order_Items["quantity"].describe()

count    125812.000000
mean          3.999213
std           2.000272
min           1.000000
25%           2.000000
50%           4.000000
75%           6.000000
max           7.000000
Name: quantity, dtype: float64

In [118]:
Order_Items = Order_Items[Order_Items["quantity"] > 0]
# Jo values chahiye rows me

In [127]:
Order_Items.isnull().sum()

order_item_id    0
order_id         0
product_id       0
quantity         0
unit_price       0
dtype: int64

In [126]:
Order_Items = Order_Items.dropna()

In [128]:
Order_Items.to_csv("Order_Items_Clean.csv", index=False)

In [ ]:
# Cleaning Products Table

In [156]:
Products.isnull().sum()

product_id    0
category      0
price         0
brand         0
stock         0
dtype: int64

In [145]:
Products["brand"].value_counts(dropna=False)

brand
Boat       1367
NaN        1365
Samsung    1353
sony       1340
Nike       1312
Sony       1263
Name: count, dtype: int64

In [146]:
Products["category"].value_counts(dropna=False)

category
Fashion        1172
Home           1165
Electronics    1157
Beauty         1138
electronics    1126
NaN            1121
Sports         1121
Name: count, dtype: int64

In [147]:
Products["brand"] = Products["brand"].str.strip()
Products["brand"] = Products["brand"].str.title()

In [148]:
Products["brand"].value_counts(dropna=False)

brand
Sony       2603
Boat       1367
NaN        1365
Samsung    1353
Nike       1312
Name: count, dtype: int64

In [149]:
Products["category"] = Products["category"].str.strip()
Products["category"] = Products["category"].str.title()

In [150]:
Products["category"].value_counts(dropna=False)

category
Electronics    2283
Fashion        1172
Home           1165
Beauty         1138
NaN            1121
Sports         1121
Name: count, dtype: int64

In [155]:
Products.head(10)

  product_id     category    price    brand  stock
0    P000000      Fashion   889.61     Sony    621
1    P000001  Electronics   313.84     Boat    465
2    P000002      Fashion   607.57     Boat    153
3    P000003       Beauty   168.39     Boat    956
4    P000004  Electronics   900.85  Samsung    913
5    P000005         Home   136.93     Sony     85
6    P000006      Fashion  2036.65  Unknown    520
7    P000007      Unknown   349.10  Samsung    820
8    P000008  Electronics   576.32     Nike    639
9    P000009      Fashion   429.67  Samsung    292

In [154]:
Products["category"] = Products["category"].fillna("Unknown")
Products["brand"] = Products["brand"].fillna("Unknown")

In [157]:
Products.to_csv("Products_Clean.csv",index=False)

In [158]:
# Cleaning Payments Table

In [168]:
Payments.isnull().sum()

payment_id        0
order_id          0
payment_method    0
amount            0
dtype: int64

In [166]:
Payments["payment_method"].value_counts(dropna=False)

payment_method
UPI           33156
NetBanking    16796
COD           16784
Card          16714
Unknown       16550
Name: count, dtype: int64

In [163]:
Payments["payment_method"] = Payments["payment_method"].replace("upi","UPI")

In [165]:
Payments["payment_method"] = Payments["payment_method"].fillna("Unknown")

In [167]:
Payments = Payments.dropna(subset=["amount"])

In [169]:
Payments.to_csv("Payment_Clean.csv",index=False)

In [ ]:
# Summary

# Customers
# - Removed 500 duplicate records
# - Standardized city names
# - Replaced missing city values with 'Unknown'

# Orders
# - Standardized order status values
# - Replaced missing status values with 'Unknown'
# - Removed 1000 duplicate records

# Order_Items
# - Removed records with quantity <= 0
# - Removed records with missing unit_price

# Products
# - Standardized category values
# - Filled missing category and brand with 'Unknown'

# Payments
# - Standardized payment methods
# - Filled missing payment methods with 'Unknown'
# - Removed records with missing amount